services:
    Tms\Bundle\ThemeBundle\Theme\ThemeRegistry: ~
    Tms\Bundle\ThemeBundle\Translation\ThemeTranslator: ~

    Tms\Bundle\ThemeBundle\Theme\ThemeManager:
        arguments:
            $themeRegistry: '@Tms\Bundle\ThemeBundle\Theme\ThemeRegistry'

    Tms\Bundle\ThemeBundle\Twig\ThemeExtension:
        arguments:
            $router: '@router'
            $themeManager : '@Tms\Bundle\ThemeBundle\Theme\ThemeManager'
        tags:
            - { name: twig.extension }

    Tms\Bundle\ThemeBundle\Twig\ThemeLoader:
        arguments:
            $bundles: '%kernel.bundles%'
            $rootPath: '%kernel.root_dir%/..'
            $themeManager : '@Tms\Bundle\ThemeBundle\Theme\ThemeManager'
        tags:
            - { name: twig.loader, priority: 50 }

    Tms\Bundle\ThemeBundle\Request\ParamConverter\ThemeParamConverter:
        arguments:
            $themeRegistry: '@Tms\Bundle\ThemeBundle\Theme\ThemeRegistry'
        tags:
            - { name: request.param_converter, priority: -2, converter: theme_converter }

# Alias
    tms_theme.helper:
        alias: Tms\Bundle\ThemeBundle\Theme\ThemeManager
        public: true
